"""cnes_profissional_registro

Revision ID: b676997e0213
Revises: 0001
Create Date: 2026-03-30 11:51:01.659530
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b676997e0213'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cnes_profissionais', sa.Column('registro', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cnes_profissionais', 'registro')
    # ### end Alembic commands ###
